### ISSUE TITLE
Attempt at starting server fails

### ISSUE THREAD

**Issue by nicobieber99** [facebookresearch/doc-storygen-v2#5]
Hi ,I have attempted to use the framework to generate a premise however I cannot even start the servers.

I have attempted the following steps:

- Clone the repo to a clean environment (ucloud VM)
- Follow the pip installs
- Clone the Llama-7b-chat-hf from huggingface
- Set the TODO path to the cloned model directory in config.yaml
- Run: `python start_servers.py --step premise`
- This gives me an error like this:
`ImportError: /home/ucloud/testenv/lib/python3.10/site-packages/vllm/cache_ops.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEEbbNS6_INS5_12MemoryFormatEEE`

This led me to attempt upgrading the vllm library to see if it would change anything which it did. I am currently stuck at the following error:
` File "/home/ucloud/testenv/lib/python3.10/site-packages/vllm/model_executor/weight_utils.py", line 251, in hf_model_weights_iterator
    with safe_open(st_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge`

I have read that this can be due to memory limitations, however I have double checked and that should not be the case. I have tried finding other causes for this but haven't found anything...
I have also attempted to re-download the model weights from huggingface, but it did not make a difference.

Have I missed anything/forgotten anything?

Here is the LLM config:
`Initializing an LLM engine with config: model='../../Llama-2-7b-chat-hf', tokenizer='../../Llama-2-7b-chat-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)`

Any help is much appreciated!

**Comment by yangkevin2** [comment]
If I'm not mistaken, this seems like an issue with either your vllm or CUDA setup rather than with the code in this repo? This repo doesn't do anything special with either vllm or CUDA - it might be more helpful to you to open an issue and ask in the vllm repo? I don't think I ever saw this error so I'm not too sure.

**Comment by nicobieber99** [comment]
I understand, thank you for answering so quickly!

**Comment by nicobieber99** [comment]
Hi again @yangkevin2 
Out of curiosity, to simply run the servers, how many/what GPUs did you use for this repo?
Was it also the 8× A100 80G GPUs that you used for training or do you have any idea what the minimal GPU specs for simply running the servers and a premise generation might be?

I have been trying with a 16GB Nvidia T4 but it is causing some (memory) problems with vllm currently which I am trying to resolve with the community there.

Thank you!

**Comment by yangkevin2** [comment]
IIRC I ran on one 80G GPU. You could probably modify the code in https://github.com/facebookresearch/doc-storygen-v2/blob/main/storygen/common/server.py to load the model in lower precision for inference to use less memory, or split up across multiple GPUs, but I'm not sure if a single 16GB GPU would be enough unfortunately.
